{{- if not .Values.krakend.allInOneImage }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "krakend.fullname" . }}-partials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
{{- if .Values.krakend.partialsDirSource }}
binaryData:
{{- range $path, $_ := .Files.Glob .Values.krakend.partialsDirSource }}
  {{ regexReplaceAll "(.*)/" $path "" }}: |-
{{ $.Files.Get $path | b64enc | indent 4 }}
{{- end }}
{{- else }}

data:
  {{- range $key, $value := .Values.krakend.partials }}
  {{ $key }}: |-
    {{ $value | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
