{{- if not .Values.krakend.allInOneImage }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "krakend.fullname" . }}-partials
data:
  {{- range $key, $value := .Values.krakend.partials }}
  {{ $key }}: |-
    {{ $value | nindent 4 }}
  {{- end }}
  {{- end }}