kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "krakend.fullname" . }}-templates
data:
  {{- range $key, $value := .Values.krakend.templates }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
