{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "krakend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ required "gateway.gatewayClassName is required when gateway.enabled is true" .Values.gateway.gatewayClassName }}
  listeners:
    {{- toYaml .Values.gateway.listeners | nindent 4 }}
{{- end }}
