{{- if .Values.podDisruptionBudget.enabled -}}
{{- $replicas := .Values.replicaCount }}
{{- if and .Values.autoscaling.enabled (not .Values.keda.enabled) }}
{{- $replicas = .Values.autoscaling.minReplicas }}
{{- else if and .Values.keda.enabled (not .Values.autoscaling.enabled) }}
{{- $replicas = .Values.keda.minReplicas }}
{{- end }}
{{- if gt ($replicas | int) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- if not (eq .Values.podDisruptionBudget.unhealthyPodEvictionPolicy "") }}
  unhealthyPodEvictionPolicy: {{ .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "krakend.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
