{{ if .Values.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "krakend.fullname" . }}
  labels: {{- include "krakend.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
    {{- range $key, $value := .Values.serviceMonitor.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "krakend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.serviceMonitor.targetPort }}
{{- end }}
