apiVersion: v1
kind: Service
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
  {{- if coalesce .Values.service.annotations .Values.openshift.trustSignerCA }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
    {{- if .Values.openshift.trustSignerCA }}
    service.beta.openshift.io/serving-cert-secret-name: {{ include "krakend.fullname" . }}-service-cert
    {{- end}}
  {{- end }}
spec:
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "krakend.selectorLabels" . | nindent 4 }}
